# Generated by Django 5.0.3 on 2024-05-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_stack_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='definition',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='term',
            field=models.CharField(max_length=400),
        ),
    ]
