# Generated by Django 5.1.4 on 2025-01-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_alter_flashcard_definition_alter_flashcard_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='term',
            field=models.CharField(max_length=500),
        ),
    ]
